# piki-ai — see PLAN.md
#
#   make          development binaries (dynamic, system OpenSSL)
#   make test     tests (normal build + AddressSanitizer/UBSan)
#   make clean
#
#   make release  static release binaries (dist/piki-linux-{x86_64,i686})
#                 via tools/build-release.sh: musl + static OpenSSL, with the
#                 i686-linux-musl toolchain and the tarballs cached in deps/.
# On Haiku the build is native; the -lnetwork is added automatically, and
# on x86 (32-bit) the legacy gcc2 (kept for BeOS ABI compat, no -std=c99/
# -Wextra/-MP) is swapped for the modern gcc-x86 secondary compiler
# unless CC was given explicitly (`pkgman install gcc_x86` if missing).

CC       ?= cc
CFLAGS   ?= -O2
WARN     := -std=c99 -Wall -Wextra
CPPFLAGS += -D_POSIX_C_SOURCE=200809L
LIBS     := -lssl -lcrypto

ifeq ($(shell uname),Haiku)
LIBS += -lnetwork
ifeq ($(origin CC),default)
# Checked as plain files (not via a shell "command -v"/"which"), since
# make's $(shell ...) subshell is not guaranteed to have the same PATH
# or the same builtins as the interactive one.
HAIKU_GCC_X86 := $(firstword $(wildcard /bin/gcc-x86 \
                                        /boot/system/bin/gcc-x86 \
                                        /boot/system/non-packaged/bin/gcc-x86))
ifneq ($(HAIKU_GCC_X86),)
CC := $(HAIKU_GCC_X86)
endif
endif
endif

B    := build
OBJS := $(B)/buf.o $(B)/net.o $(B)/http.o $(B)/json.o $(B)/sse.o \
        $(B)/api.o $(B)/chat.o $(B)/config.o $(B)/term.o $(B)/edit.o \
        $(B)/tools.o $(B)/md.o $(B)/web.o

all: $(B)/piki $(B)/tlsprobe

$(B)/piki: $(B)/main.o $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

# Statically-linked piki against whatever OpenSSL is present (system static
# libs). Used by CI inside Alpine; override LIBS with `pkg-config --static`.
# For a portable cross build (x86_64 + i686 from this machine) use
# `make release` / tools/build-release.sh instead.
$(B)/piki-static: $(B)/main.o $(OBJS)
	$(CC) $(CFLAGS) -static -o $@ $^ $(LIBS)

static: $(B)/piki-static

$(B)/tlsprobe: $(B)/tlsprobe.o $(B)/buf.o $(B)/net.o
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

$(B)/%.o: src/%.c | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -MMD -MP -c -o $@ $<

$(B):
	mkdir -p $(B)

# Regenerated by hand with tools/mkcerts.sh when the CA roots rotate.
src/certs.h:
	tools/mkcerts.sh

$(B)/net.o: src/certs.h

# --- tests -------------------------------------------------------------

SAN := -g -O1 -fsanitize=address,undefined -fno-omit-frame-pointer

SRC_test_buf  := tests/test_buf.c src/buf.c
SRC_test_md   := tests/test_md.c src/md.c src/buf.c
SRC_test_web  := tests/test_web.c src/web.c src/http.c src/net.c \
                 src/json.c src/buf.c
SRC_test_json := tests/test_json.c src/json.c src/buf.c
SRC_test_http := tests/test_http.c src/http.c src/buf.c src/net.c
SRC_test_sse  := tests/test_sse.c src/sse.c src/buf.c
SRC_test_chat := tests/test_chat.c src/chat.c src/json.c src/buf.c
SRC_test_conf := tests/test_config.c src/config.c src/buf.c
SRC_test_edit := tests/test_edit.c src/edit.c src/buf.c
SRC_test_tool := tests/test_tools.c src/tools.c src/json.c src/buf.c
SRC_test_api := tests/test_api.c src/api.c src/chat.c src/json.c \
                src/http.c src/sse.c src/net.c src/buf.c

$(B)/test_buf: $(SRC_test_buf) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_buf)
$(B)/test_buf.asan: $(SRC_test_buf) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_buf)

$(B)/test_md: $(SRC_test_md) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_md)
$(B)/test_md.asan: $(SRC_test_md) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_md)

$(B)/test_web: $(SRC_test_web) src/certs.h | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_web) $(LIBS)
$(B)/test_web.asan: $(SRC_test_web) src/certs.h | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_web) $(LIBS)

$(B)/test_json: $(SRC_test_json) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_json)
$(B)/test_json.asan: $(SRC_test_json) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_json)

$(B)/test_http: $(SRC_test_http) src/certs.h | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_http) $(LIBS)
$(B)/test_http.asan: $(SRC_test_http) src/certs.h | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_http) $(LIBS)

$(B)/test_sse: $(SRC_test_sse) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_sse)
$(B)/test_sse.asan: $(SRC_test_sse) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_sse)

$(B)/test_chat: $(SRC_test_chat) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_chat)
$(B)/test_chat.asan: $(SRC_test_chat) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_chat)

$(B)/test_config: $(SRC_test_conf) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_conf)
$(B)/test_config.asan: $(SRC_test_conf) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_conf)

$(B)/test_edit: $(SRC_test_edit) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_edit)
$(B)/test_edit.asan: $(SRC_test_edit) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_edit)

$(B)/test_tools: $(SRC_test_tool) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_tool)
$(B)/test_tools.asan: $(SRC_test_tool) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_tool)

$(B)/test_api: $(SRC_test_api) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(CFLAGS) -Isrc -o $@ $(SRC_test_api) $(LIBS)
$(B)/test_api.asan: $(SRC_test_api) | $(B)
	$(CC) $(WARN) $(CPPFLAGS) $(SAN) -Isrc -o $@ $(SRC_test_api) $(LIBS)

TESTBINS := $(B)/test_buf $(B)/test_buf.asan \
            $(B)/test_md $(B)/test_md.asan \
            $(B)/test_web $(B)/test_web.asan \
            $(B)/test_json $(B)/test_json.asan \
            $(B)/test_http $(B)/test_http.asan \
            $(B)/test_sse $(B)/test_sse.asan \
            $(B)/test_chat $(B)/test_chat.asan \
            $(B)/test_config $(B)/test_config.asan \
            $(B)/test_edit $(B)/test_edit.asan \
            $(B)/test_tools $(B)/test_tools.asan \
            $(B)/test_api $(B)/test_api.asan

test: $(TESTBINS)
	@$(B)/test_buf
	@$(B)/test_buf.asan
	@$(B)/test_md
	@$(B)/test_md.asan
	@$(B)/test_web
	@$(B)/test_web.asan
	@$(B)/test_json
	@$(B)/test_json.asan
	@$(B)/test_http
	@$(B)/test_http.asan
	@$(B)/test_sse
	@$(B)/test_sse.asan
	@$(B)/test_chat
	@$(B)/test_chat.asan
	@$(B)/test_config
	@$(B)/test_config.asan
	@$(B)/test_edit
	@$(B)/test_edit.asan
	@$(B)/test_tools
	@$(B)/test_tools.asan
	@$(B)/test_api
	@$(B)/test_api.asan

release:
	sh tools/build-release.sh

clean:
	rm -rf $(B)

-include $(B)/*.d

.PHONY: all test clean release static
