#!/bin/sh
# Generates src/certs.h (CA roots embedded in the binary) from a system
# PEM bundle.
#
# Usage: tools/mkcerts.sh [--minimal] [bundle.pem]
#        (default bundle: /etc/ssl/cert.pem)
#
# By default EVERY root in the bundle is embedded (~120 roots, ~250 KB):
# the fetch_url web tool can reach arbitrary HTTPS hosts, so the full
# store is needed. --minimal keeps only the curated list that covers the
# built-in endpoints (OpenRouter, GitHub update check, Meta) for a
# smaller binary without the web tools' reach.
set -eu

cd "$(dirname "$0")/.."
MODE=full
if [ "${1:-}" = "--minimal" ]; then
    MODE=minimal
    shift
fi
BUNDLE="${1:-/etc/ssl/cert.pem}"
OUT=src/certs.h
TMP="$(mktemp)"
TMPD="$(mktemp -d)"
trap 'rm -rf "$TMP" "$TMPD"' EXIT

[ -r "$BUNDLE" ] || { echo "cannot read $BUNDLE" >&2; exit 1; }

{
    echo "/* Generated by tools/mkcerts.sh -- DO NOT EDIT BY HAND."
    echo " * Trusted CA roots embedded in the binary. */"
    echo "#ifndef PIKI_CERTS_H"
    echo "#define PIKI_CERTS_H"
    echo
    echo "static const char *const piki_ca_roots[] = {"
} > "$OUT"

COUNT=0

emit_cert() { # $1 = pem file, $2 = label
    openssl x509 -in "$1" -noout || {
        echo "invalid PEM for '$2'" >&2; exit 1; }
    {
        printf '/* %s */\n' "$2"
        sed 's/.*/"&\\n"/' "$1"
        echo ","
    } >> "$OUT"
    COUNT=$((COUNT + 1))
}

if [ "$MODE" = minimal ]; then
    # Google Trust Services (openrouter.ai via Cloudflare) + Let's Encrypt
    # in case they rotate. USERTrust/Sectigo cover api.github.com (the
    # update check). DigiCert covers api.meta.ai.
    set -- \
        "GTS Root R1" "GTS Root R3" "GTS Root R4" \
        "ISRG Root X1" "ISRG Root X2" \
        "USERTrust ECC Certification Authority" \
        "USERTrust RSA Certification Authority" \
        "Sectigo Public Server Authentication Root E46" \
        "Sectigo Public Server Authentication Root R46" \
        "DigiCert Global Root G2" "DigiCert Global Root G3"
    for name; do
        awk -v label="# $name" '
            $0 == label {want = 1; next}
            want && /-----BEGIN CERTIFICATE-----/ {cap = 1}
            cap {print}
            cap && /-----END CERTIFICATE-----/ {exit}
        ' "$BUNDLE" > "$TMP"
        grep -q 'END CERTIFICATE' "$TMP" || {
            echo "root '$name' not found in $BUNDLE" >&2; exit 1; }
        emit_cert "$TMP" "$name"
    done
else
    # Split the bundle into one file per BEGIN/END block; do not rely on
    # the '# name' comment labels, which vary across distros.
    awk -v dir="$TMPD" '
        /-----BEGIN CERTIFICATE-----/ {n++; cap = 1}
        cap {print > sprintf("%s/%05d.pem", dir, n)}
        /-----END CERTIFICATE-----/ {cap = 0}
    ' "$BUNDLE"
    found=0
    for pem in "$TMPD"/*.pem; do
        [ -f "$pem" ] || continue
        found=1
        label="$(openssl x509 -in "$pem" -noout -subject -nameopt sep_multiline 2>/dev/null |
                 awk -F= '/CN=|OU=|O=/ {v = $2} END {print v}')"
        [ -n "$label" ] || label="unnamed root"
        # keep the label safe inside a C block comment
        label="$(printf '%s' "$label" | tr -d '*/' | tr -c 'A-Za-z0-9 .()+,:-' ' ')"
        emit_cert "$pem" "$label"
    done
    [ "$found" = 1 ] || { echo "no certificates in $BUNDLE" >&2; exit 1; }
fi

{
    echo "};"
    echo
    echo "#define PIKI_CA_ROOTS_COUNT \\"
    echo "    (sizeof(piki_ca_roots) / sizeof(piki_ca_roots[0]))"
    echo
    echo "#endif /* PIKI_CERTS_H */"
} >> "$OUT"

echo "generated $OUT with $COUNT roots from $BUNDLE ($MODE)"
