#!/bin/sh
# Extracts the required CA roots from a system PEM bundle and generates
# src/certs.h to embed them in the binary.
#
# Usage: tools/mkcerts.sh [bundle.pem]      (default: /etc/ssl/cert.pem)
#
# Regenerate if OpenRouter/Cloudflare rotate CA; the current chain can be seen with:
#   openssl s_client -connect openrouter.ai:443 -servername openrouter.ai
set -eu

cd "$(dirname "$0")/.."
BUNDLE="${1:-/etc/ssl/cert.pem}"
OUT=src/certs.h
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

[ -r "$BUNDLE" ] || { echo "cannot read $BUNDLE" >&2; exit 1; }

# Google Trust Services (openrouter.ai's current CA via Cloudflare) +
# Let's Encrypt in case they rotate. By trusting the GTS root directly the
# GlobalSign cross-sign that the server sends is not needed.
# USERTrust/Sectigo cover api.github.com (the update check).
set -- \
    "GTS Root R1" "GTS Root R3" "GTS Root R4" \
    "ISRG Root X1" "ISRG Root X2" \
    "USERTrust ECC Certification Authority" \
    "USERTrust RSA Certification Authority" \
    "Sectigo Public Server Authentication Root E46" \
    "Sectigo Public Server Authentication Root R46"

{
    echo "/* Generated by tools/mkcerts.sh -- DO NOT EDIT BY HAND."
    echo " * Trusted CA roots embedded in the binary. */"
    echo "#ifndef PIKI_CERTS_H"
    echo "#define PIKI_CERTS_H"
    echo
    echo "static const char *const piki_ca_roots[] = {"
} > "$OUT"

for name; do
    awk -v label="# $name" '
        $0 == label {want = 1; next}
        want && /-----BEGIN CERTIFICATE-----/ {cap = 1}
        cap {print}
        cap && /-----END CERTIFICATE-----/ {exit}
    ' "$BUNDLE" > "$TMP"
    grep -q 'END CERTIFICATE' "$TMP" || {
        echo "root '$name' not found in $BUNDLE" >&2; exit 1; }
    openssl x509 -in "$TMP" -noout || {
        echo "invalid PEM for '$name'" >&2; exit 1; }
    {
        printf '/* %s */\n' "$name"
        sed 's/.*/"&\\n"/' "$TMP"
        echo ","
    } >> "$OUT"
done

{
    echo "};"
    echo
    echo "#define PIKI_CA_ROOTS_COUNT \\"
    echo "    (sizeof(piki_ca_roots) / sizeof(piki_ca_roots[0]))"
    echo
    echo "#endif /* PIKI_CERTS_H */"
} >> "$OUT"

echo "generated $OUT with $# roots from $BUNDLE"
